package com.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    READCOMPANIES,
    CREATECOMPANIES,
    DELETECOMPANIES,
    UPDATECOMPANIES,
    READRESEARCHES,
    CREATERESEARCHES,
    DELETERESEARCHES,
    UPDATERESEARCHES,
    COUNTRESEARCHES,
    READEMPLOYEES,
    CREATEEMPLOYEES,
    DELETEEMPLOYEES,
    UPDATEEMPLOYEES,
    READUSERS,
    CREATEUSERS,
    DELETEUSERS,
    UPDATEUSERS,
    SEXDIAGRAM,
    PRICEDIAGRAM,
    SALARYDIAGRAM
}
